### ISSUE TITLE
Self tests failures during build

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12-nsg#44]
Current gpkg12-nsg-0.6-SNAPSHOT 2018/09/21 fails self-tests:

Failed tests:
  MetadataTestsTest.testWithOneInvalidAndOneValidEntry:65 Validation of the NMIS v2.2 metadata as XML failed: Invalid byte 1 of 1-byte UTF-8 sequence.
  MetadataTestsTest.testWithOneValidEntry:55 Validation of the NMIS v2.2 metadata as XML failed: Invalid byte 1 of 1-byte UTF-8 sequence.

--------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest
[Fatal Error] :-1:-1: Premature end of file.
Sep 21, 2018 1:42:00 PM org.opengis.cite.gpkg12.nsg.metadata.MetadataTests validateXmlEntry
WARNING: An error occurred during validation.
org.xml.sax.SAXParseException; lineNumber: 129; columnNumber: 49; Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.xerces.jaxp.validation.Util.toSAXParseException(Unknown Source)
        at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
        at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
        at javax.xml.validation.Validator.validate(Validator.java:124)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validate(MetadataTests.java:152)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validateXmlEntry(MetadataTests.java:98)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validateXmlEntries(MetadataTests.java:88)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest.testWithOneInvalidAndOneValidEntry(MetadataTestsTest.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.xerces.impl.io.UTF8Reader.invalidByte(Unknown Source)
        at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.peekChar(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.scanComment(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanComment(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        ... 32 more

[Fatal Error] :1:1: Content is not allowed in prolog.
Sep 21, 2018 1:42:01 PM org.opengis.cite.gpkg12.nsg.metadata.MetadataTests validateXmlEntry
WARNING: An error occurred during validation.
org.xml.sax.SAXParseException; lineNumber: 129; columnNumber: 49; Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.xerces.jaxp.validation.Util.toSAXParseException(Unknown Source)
        at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
        at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
        at javax.xml.validation.Validator.validate(Validator.java:124)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validate(MetadataTests.java:152)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validateXmlEntry(MetadataTests.java:98)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTests.validateXmlEntries(MetadataTests.java:88)
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest.testWithOneValidEntry(MetadataTestsTest.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.xerces.impl.io.UTF8Reader.invalidByte(Unknown Source)
        at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.peekChar(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.scanComment(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanComment(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        ... 32 more

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.918 sec <<< FAILURE! - in org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest
testWithOneInvalidAndOneValidEntry(org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest)  Time elapsed: 2.335 sec  <<< FAILURE!
java.lang.AssertionError: Validation of the NMIS v2.2 metadata as XML failed: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest.testWithOneInvalidAndOneValidEntry(MetadataTestsTest.java:65)

testWithOneValidEntry(org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest)  Time elapsed: 0.189 sec  <<< FAILURE!
java.lang.AssertionError: Validation of the NMIS v2.2 metadata as XML failed: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.opengis.cite.gpkg12.nsg.metadata.MetadataTestsTest.testWithOneValidEntry(MetadataTestsTest.java:55)

**Comment by lgoltz** [comment]
@ajanett I've checked the jenkins build, but the failure does not occur. Same on my local environment (tested with mvn and IntelliJ).

**Comment by ajanett** [comment]
@lgoltz   Interesting. I am building with mvn; not a Docker build. But I am building now in a limited environment (i.e. I recently deleted all mvn repositories) where I've only built geopackage and WFS and the dependencies needed for them.  Well, maybe if someone else sees this there will be some additional clues.

Thanks you for trying. No real need to push this issue further.
